apiVersion: apps/v1
kind: Deployment #This indicates the resource type being created
metadata:
  name: kubernetes-demo
spec:
  selector:
    matchLabels:
      app: kubernetes-demo
  replicas: 2 #This indicates the number of replicas to be created
  template:
    metadata:
      labels:
        app: kubernetes-demo
    spec:
      containers:
        - name: kubernetes-demo
          image: kubernetes-demo:1.0 #Image to be used by the containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 #Port that the container is running in the cluster